"""empty message

Revision ID: 0b089262f49a
Revises: e7eb0e0c5323
Create Date: 2026-01-12 17:49:55.186979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b089262f49a'
down_revision = 'e7eb0e0c5323'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_trips', sa.Column('estimated_arrival', sa.DateTime(), nullable=True))
    op.add_column('driver_trips', sa.Column('start_coordinates', sa.JSON(), nullable=True))
    op.add_column('driver_trips', sa.Column('finish_coordinates', sa.JSON(), nullable=True))
    op.add_column('driver_trips', sa.Column('route_polyline', sa.Text(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver_trips', 'route_polyline')
    op.drop_column('driver_trips', 'finish_coordinates')
    op.drop_column('driver_trips', 'start_coordinates')
    op.drop_column('driver_trips', 'estimated_arrival')
    # ### end Alembic commands ###