"""add estimated_arrival and map fields

Revision ID: 11366eaaa0d7
Revises: 23dc198db38b
Create Date: 2026-01-12 18:29:37.673027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11366eaaa0d7'
down_revision = '23dc198db38b'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###