"""add estimated_arrival field to driver_trips

Revision ID: 23dc198db38b
Revises: 0b089262f49a
Create Date: 2026-01-12 18:13:26.449125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23dc198db38b'
down_revision = '0b089262f49a'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###