"""initial_tables

Revision ID: e7eb0e0c5323
Revises: 7e8fe4dcae45
Create Date: 2026-01-08 23:35:11.780084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7eb0e0c5323'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('language_code', sa.String(length=10), nullable=True),
    sa.Column('car_model', sa.String(length=100), nullable=True),
    sa.Column('car_color', sa.String(length=50), nullable=True),
    sa.Column('car_plate', sa.String(length=20), nullable=True),
    sa.Column('car_type', sa.Enum('SEDAN', 'HATCHBACK', 'SUV', 'MINIVAN', 'OTHER', name='cartype'), nullable=True),
    sa.Column('car_year', sa.Integer(), nullable=True),
    sa.Column('car_seats', sa.Integer(), nullable=True),
    sa.Column('has_car', sa.Boolean(), nullable=True),
    sa.Column('driver_rating', sa.Float(), nullable=True),
    sa.Column('passenger_rating', sa.Float(), nullable=True),
    sa.Column('total_driver_trips', sa.Integer(), nullable=True),
    sa.Column('total_passenger_trips', sa.Integer(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.Enum('DRIVER', 'PASSENGER', 'BOTH', name='userrole'), nullable=True),
    sa.Column('is_bot', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('driver_trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('departure_date', sa.DateTime(), nullable=False),
    sa.Column('departure_time', sa.String(length=10), nullable=True),
    sa.Column('start_address', sa.String(length=500), nullable=False),
    sa.Column('start_lat', sa.Float(), nullable=True),
    sa.Column('start_lng', sa.Float(), nullable=True),
    sa.Column('start_city', sa.String(length=100), nullable=True),
    sa.Column('finish_address', sa.String(length=500), nullable=False),
    sa.Column('finish_lat', sa.Float(), nullable=True),
    sa.Column('finish_lng', sa.Float(), nullable=True),
    sa.Column('finish_city', sa.String(length=100), nullable=True),
    sa.Column('route_points', sa.JSON(), nullable=True),
    sa.Column('route_distance', sa.Float(), nullable=True),
    sa.Column('route_duration', sa.Integer(), nullable=True),
    sa.Column('polyline', sa.Text(), nullable=True),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.Column('price_per_seat', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('max_passengers_back', sa.Integer(), nullable=True),
    sa.Column('allow_smoking', sa.Boolean(), nullable=True),
    sa.Column('allow_animals', sa.Boolean(), nullable=True),
    sa.Column('allow_luggage', sa.Boolean(), nullable=True),
    sa.Column('allow_music', sa.Boolean(), nullable=True),
    sa.Column('allow_stops', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', 'IN_PROGRESS', name='tripstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_trips_id'), 'driver_trips', ['id'], unique=False)
    op.create_table('passenger_trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passenger_id', sa.Integer(), nullable=False),
    sa.Column('desired_date', sa.DateTime(), nullable=False),
    sa.Column('desired_time', sa.String(length=10), nullable=True),
    sa.Column('time_flexibility', sa.Integer(), nullable=True),
    sa.Column('start_address', sa.String(length=500), nullable=False),
    sa.Column('start_lat', sa.Float(), nullable=True),
    sa.Column('start_lng', sa.Float(), nullable=True),
    sa.Column('start_city', sa.String(length=100), nullable=True),
    sa.Column('finish_address', sa.String(length=500), nullable=False),
    sa.Column('finish_lat', sa.Float(), nullable=True),
    sa.Column('finish_lng', sa.Float(), nullable=True),
    sa.Column('finish_city', sa.String(length=100), nullable=True),
    sa.Column('required_seats', sa.Integer(), nullable=True),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('preferred_gender', sa.String(length=10), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', 'IN_PROGRESS', name='tripstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['passenger_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passenger_trips_id'), 'passenger_trips', ['id'], unique=False)
    op.create_table('user_cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('license_plate', sa.String(length=20), nullable=True),
    sa.Column('car_type', sa.String(length=20), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_plate')
    )
    op.create_index(op.f('ix_user_cars_id'), 'user_cars', ['id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_trip_id', sa.Integer(), nullable=False),
    sa.Column('passenger_trip_id', sa.Integer(), nullable=True),
    sa.Column('passenger_id', sa.Integer(), nullable=False),
    sa.Column('booked_seats', sa.Integer(), nullable=True),
    sa.Column('price_agreed', sa.Float(), nullable=True),
    sa.Column('meeting_point', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', 'IN_PROGRESS', name='tripstatus'), nullable=True),
    sa.Column('booked_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_trip_id'], ['driver_trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['passenger_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['passenger_trip_id'], ['passenger_trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_user_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('punctuality', sa.Integer(), nullable=True),
    sa.Column('comfort', sa.Integer(), nullable=True),
    sa.Column('communication', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_user_cars_id'), table_name='user_cars')
    op.drop_table('user_cars')
    op.drop_index(op.f('ix_passenger_trips_id'), table_name='passenger_trips')
    op.drop_table('passenger_trips')
    op.drop_index(op.f('ix_driver_trips_id'), table_name='driver_trips')
    op.drop_table('driver_trips')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###